# Site settings
title: Dr. Olav Schettler
email: olav@schettler.net
description: "I am a software engineer, book author, and educator from Bonn, Germany."
skills:
  - Software Engineer
  - Book Author
  - Educator

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  
# Footer settings
footer:
  copyright: Dr. Olav Schettler
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: google-plus
    url: https://plus.google.com/+OlavSchettlerBonn
  - title: twitter
    url: http://twitter.com/oschettler
  - title: stack-overflow
    url: http://stackoverflow.com/users/125395/olav
  - title: bitbucket 
    url: https://bitbucket.org/olav
  - title: github
    url: https://github.com/oschettler

# Postal address (add as many lines as necessary)
address:
  - line: Bonn, Germany
  
# Credits content
credits:
  - line: Freelance theme by <a href="http://startbootstrap.com">Start Bootstrap</a>.
  - line: Site scaffolding by <a href="https://github.com/jeromelachaud/freelancer-theme">Jerome Lachaud</a>.
  - line: Site generator by <a href="https://dossier.pm" title="A generator for beautiful and up to date portfolio sites">me ;)</a>

# Build settings
markdown: kramdown
permalink: pretty
